#!/usr/bin/env python3
"""
Audio Validation Script

Features:
1. Read the audio list section from the storyboard script
2. Verify audio files exist and have valid durations
3. Read sync_points from audio_info.json (sentence-level sync points)
4. Update the duration column in the storyboard script
5. Print sync points summary for each scene, convenient for use with wait_for_narration() in play_scene_X()
6. If length is missing or abnormal, report an error

Usage:
    python validate_audio.py storyboard.md ./audio

Output:
    - Updated storyboard.md (duration column filled)
    - audio/audio_info.json (Generated by generate_tts.py, this script only validates)
"""

import sys
import os
import re
import json
from pathlib import Path


def parse_storyboard(storyboard_path):
    """
    Parse storyboard script to extract the audio list section

    Returns: list of dict, each dict contains scene number, filename, narration text, etc.
    """
    with open(storyboard_path, 'r', encoding='utf-8') as f:
        content = f.read()

    # Find audio generation list table
    # Supported format: | Scene | Filename | Narration Text | Duration | Speaker | Emotion |
    pattern = r'##\s*Audio Generation List.*?(?=##|$)'
    match = re.search(pattern, content, re.DOTALL)
    
    if not match:
        # Fallback to Chinese title if not translated yet
        pattern = r'##\s*音频生成清单.*?(?=##|$)'
        match = re.search(pattern, content, re.DOTALL)

    if not match:
        print("Warning: Audio Generation List section not found")
        return [], content

    section = match.group(0)
    lines = section.split('\n')

    audio_list = []
    for line in lines:
        line = line.strip()
        # Match table rows
        if line.startswith('|') and not line.startswith('|---'):
            parts = [p.strip() for p in line.split('|') if p.strip()]
            if len(parts) >= 2 and parts[0].isdigit():
                # Parse table row
                scene_num = int(parts[0])
                filename = parts[1] if len(parts) > 1 else ""
                text = parts[2] if len(parts) > 2 else ""
                duration_str = parts[3] if len(parts) > 3 else ""
                speaker = parts[4] if len(parts) > 4 else "xiaoxiao"
                emotion = parts[5] if len(parts) > 5 else "calm"

                # Parse duration (could be empty string or number)
                duration = None
                if duration_str:
                    try:
                        # Supported formats: 8, 8s, 8.5, 8.5s, 8秒
                        duration = float(duration_str.replace('s', '').replace('秒', '').replace('sec', ''))
                    except ValueError:
                        duration = None

                audio_list.append({
                    'scene': scene_num,
                    'file': filename,
                    'text': text,
                    'duration': duration,
                    'speaker': speaker,
                    'emotion': emotion
                })

    return audio_list, content


def get_audio_duration(audio_path):
    """
    Get audio file duration (seconds)

    Try the following methods (in priority):
    1. mutagen (supports various formats)
    2. wave (only supports wav)
    3. ffprobe (requires ffmpeg)
    """
    # Try mutagen
    try:
        from mutagen.mp3 import MP3
        from mutagen.wavpack import WavPack
        audio = MP3(audio_path)
        return audio.info.length
    except:
        pass

    try:
        from mutagen.wave import WAVE
        audio = WAVE(audio_path)
        return audio.info.length
    except:
        pass

    # Try wave module
    try:
        import wave
        with wave.open(audio_path, 'rb') as wf:
            frames = wf.getnframes()
            rate = wf.getframerate()
            return frames / float(rate)
    except:
        pass

    # Try ffprobe
    try:
        import subprocess
        result = subprocess.run(
            ['ffprobe', '-v', 'error', '-show_entries', 'format=duration',
             '-of', 'default=noprint_wrappers=1:nokey=1', audio_path],
            capture_output=True, text=True
        )
        if result.returncode == 0:
            return float(result.stdout.strip())
    except:
        pass

    return None


def validate_audio_files(audio_list, audio_dir):
    """
    Validate audio files

    Returns: (valid, errors, updated_list)
    - valid: bool, if all passed
    - errors: list of str, error messages
    - updated_list: updated audio list with durations
    """
    errors = []
    updated_list = []
    valid = True

    for item in audio_list:
        scene_num = item['scene']
        filename = item['file']
        audio_path = os.path.join(audio_dir, filename)

        # Check if file exists
        if not os.path.exists(audio_path):
            errors.append(f"❌ Error: Scene {scene_num} audio file not found: {filename}")
            valid = False
            updated_list.append(item)
            continue

        # Get actual duration
        actual_duration = get_audio_duration(audio_path)

        if actual_duration is None:
            errors.append(f"❌ Error: Scene {scene_num} failed to get audio duration: {filename}")
            valid = False
            updated_list.append(item)
            continue

        if actual_duration <= 0:
            errors.append(f"❌ Error: Scene {scene_num} abnormal audio duration ({actual_duration:.2f}s): {filename}")
            valid = False
            updated_list.append(item)
            continue

        if actual_duration < 1.0:
            errors.append(f"⚠️ Warning: Scene {scene_num} audio duration too short ({actual_duration:.2f}s): {filename}")

        # Update duration
        updated_item = item.copy()
        updated_item['duration'] = round(actual_duration, 2)
        updated_list.append(updated_item)

        print(f"✓ Scene {scene_num}: {filename} - {actual_duration:.2f}s")

    return valid, errors, updated_list


def generate_audio_info_json(updated_list, audio_dir):
    """Generate audio_info.json file"""
    output = {
        'files': updated_list,
        'total_duration': sum(item.get('duration', 0) or 0 for item in updated_list),
        'count': len(updated_list)
    }

    output_path = os.path.join(audio_dir, 'audio_info.json')
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(output, f, ensure_ascii=False, indent=2)

    print(f"\nGenerated: {output_path}")
    return output_path


def update_storyboard(storyboard_path, original_content, updated_list):
    """Update duration column in storyboard script"""
    lines = original_content.split('\n')
    new_lines = []

    # Track currently processed audio list index
    audio_idx = 0
    in_audio_section = False

    for line in lines:
        # Detect entry into audio list section
        if 'Audio Generation List' in line or '音频生成清单' in line:
            in_audio_section = True

        if in_audio_section and line.startswith('|') and not line.startswith('|---'):
            parts = [p.strip() for p in line.split('|')]
            # Filter empty strings
            parts = [p for p in parts if p]

            if len(parts) >= 2 and parts[0].isdigit() and audio_idx < len(updated_list):
                scene_num = int(parts[0])
                if scene_num == updated_list[audio_idx]['scene']:
                    # Update duration column
                    duration = updated_list[audio_idx].get('duration')
                    if duration is not None:
                        # Rebuild table row
                        new_parts = parts[:3]  # Scene, filename, narration text
                        new_parts.append(f"{duration:.1f}")  # Duration
                        if len(parts) > 4:
                            new_parts.append(parts[4])  # Speaker
                        if len(parts) > 5:
                            new_parts.append(parts[5])  # Emotion

                        line = '| ' + ' | '.join(new_parts) + ' |'
                    audio_idx += 1

        new_lines.append(line)

    # Write back to file
    with open(storyboard_path, 'w', encoding='utf-8') as f:
        f.write('\n'.join(new_lines))

    print(f"Updated: {storyboard_path}")


def print_sync_points_summary(audio_dir, audio_list):
    """
    Read sync_points from audio_info.json and print summary.
    Useful for developers to pick wait_for_narration() keywords in play_scene_X().
    """
    info_path = os.path.join(audio_dir, 'audio_info.json')
    if not os.path.exists(info_path):
        return

    try:
        with open(info_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
    except Exception:
        return

    files = data.get('files', [])
    has_sync = any(f.get('sync_points') for f in files)
    if not has_sync:
        print("\n💡 Tip: No sync_points found in audio_info.json.")
        print("   Re-run generate_tts.py to automatically generate sentence-level sync points.")
        return

    print("\n" + "=" * 50)
    print("🎯 Sync Points Summary (for wait_for_narration)")
    print("=" * 50)

    for item in files:
        scene_num = item.get('scene', '?')
        duration = item.get('duration', 0)
        sp_list = item.get('sync_points', [])
        if not sp_list:
            continue

        print(f"\n  Scene {scene_num} ({duration:.1f}s):")
        for sp in sp_list:
            t = sp.get('time', 0)
            text = sp.get('text', '')[:35]
            print(f"    {t:6.2f}s │ \"{text}\"")


def main():
    if len(sys.argv) < 2:
        print("Usage: python validate_audio.py <storyboard.md> [audio_dir]")
        print("Example: python validate_audio.py storyboard.md ./audio")
        sys.exit(1)

    storyboard_path = sys.argv[1]
    audio_dir = sys.argv[2] if len(sys.argv) > 2 else "./audio"

    # Check files
    if not os.path.exists(storyboard_path):
        print(f"Error: Storyboard file not found: {storyboard_path}")
        sys.exit(1)

    if not os.path.exists(audio_dir):
        print(f"Error: Audio directory not found: {audio_dir}")
        sys.exit(1)

    print(f"Parsing storyboard: {storyboard_path}")
    print(f"Audio directory: {audio_dir}\n")

    # Parse storyboard
    audio_list, original_content = parse_storyboard(storyboard_path)

    if not audio_list:
        print("Audio list not found, please check storyboard script format")
        sys.exit(1)

    print(f"Found {len(audio_list)} audio entries\n")

    # Validate audio
    valid, errors, updated_list = validate_audio_files(audio_list, audio_dir)

    # Output errors
    if errors:
        print("\n" + "="*50)
        print("Validation Issues:")
        for error in errors:
            print(error)
        print("="*50)

    # Generate JSON
    if updated_list:
        generate_audio_info_json(updated_list, audio_dir)

    # Update storyboard
    if any(item.get('duration') is not None for item in updated_list):
        update_storyboard(storyboard_path, original_content, updated_list)

    # Print sync points summary
    print_sync_points_summary(audio_dir, updated_list)

    # Final Result
    print("\n" + "="*50)
    if valid:
        print("✅ Validation passed! All audio files are normal.")
        total_duration = sum(item.get('duration', 0) or 0 for item in updated_list)
        print(f"Total duration: {total_duration:.1f} seconds ({total_duration/60:.1f} minutes)")
        sys.exit(0)
    else:
        print("❌ Validation failed! Please check the errors above.")
        sys.exit(1)


if __name__ == '__main__':
    main()
